version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - surf-test-data:/data/db
  app:
    build: .
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
volumes:
  surf-test-data:
